# DEPRECATED: This file is deprecated in favor of pyproject.toml
# Please use: uv pip install -e ".[all]" or pip install -e ".[all]"
# See README.md for updated installation instructions

name: qcodes
channels:
  - conda-forge
  - anaconda
  - pypi
dependencies:
  - python>=3.7
  - qcodes
  - conda-forge::pywin32==304
  - pip>=23.1
  - scipy
  - numpy
  - pandas
  - ipykernel
  - matplotlib
  - sphinx
  - sphinx-rtd-theme
  - jupyterlab
  - notebook
  - ipykernel
  - ipython==8.15
  - jupyter_client
  - jupyter_core
  - traitlets
  - ipython_genutils
  - pip:
    - PyQt5
    - zhinst
    - qcodes_contrib_drivers
    - nidaqmx
    


